fix commented issues

diff --git a/distribution/resources/bin/gateway b/distribution/resources/bin/gateway
--- a/distribution/resources/bin/gateway
+++ b/distribution/resources/bin/gateway
@@ -51,7 +51,6 @@ JAVA_PATH=$GW_HOME/lib/jdk8u202-b08-jre
 if [ -d "$JAVA_HOME" ]; then
   echo "JAVA_HOME is externally set: $JAVA_HOME"
 else
-  echo "JAVA_HOME..."
   JAVA_HOME=$JAVA_PATH
 fi
 
@@ -87,7 +86,6 @@ fi
 
 # For Migwn, ensure paths are in UNIX format before anything is touched
 if $mingw ; then
-  echo $JAVA_HOME
   [ -n "$JAVA_HOME" ] && JAVA_HOME="`(cd "$JAVA_HOME"; pwd)`"
 fi
 
@@ -106,7 +104,7 @@ fi
 
 JDK_18=`$JAVACMD -version 2>&1 | grep "1.8."`
 if [ "$JDK_18" = "" ]; then
-    echo "Error: Microgateway is supported only on JDK 1.8"
+    echo "Error: Microgateway is supported only on Java 1.8"
     exit 1
 fi
 
@@ -118,6 +116,16 @@ fi
 if [ ! -x "$JAVACMD" ] ; then
   echo "Error: JAVA Package inside the microgateway runtime distribution is not working."
   exit 1
+fi
+
+# As we use different directory to keep microgateway configuration for the docker image
+if [ -z "$MGW_CONF_DIR" ] ; then
+    MGW_CONF_DIR="$GW_HOME/conf"
+else
+    if [ ! -d "$MGW_CONF_DIR" ] ; then
+        echo "Error: Provided Microgateway Config Directory: ${MGW_CONF_DIR} is not available"
+        exit 1
+    fi
 fi
 
 # Ballerina test/debug command
@@ -175,7 +183,7 @@ java_cmd_gateway () {
     $JAVA_OPTS \
     -Dmgw-runtime.home=${GW_HOME} \
     -Dballerina.home=${GW_HOME} \
-    -jar ${args[0]} --api.usage.data.path=$GW_HOME/api-usage-data --b7a.http.accesslog.path=$GW_HOME/logs/access_logs --b7a.config.file=$GW_HOME/conf/micro-gw.conf ${args[@]:1}  2>&1 | tee -a $GW_HOME/logs/microgateway.log
+    -jar $args --api.usage.data.path=$GW_HOME/api-usage-data --b7a.http.accesslog.path=$GW_HOME/logs/access_logs --b7a.config.file=$MGW_CONF_DIR/micro-gw.conf 2>&1 | tee -a $GW_HOME/logs/microgateway.log
 }
 
 java_cmd_gateway_background () {
@@ -188,7 +196,7 @@ java_cmd_gateway_background () {
     $JAVA_OPTS \
     -Dmgw-runtime.home=${GW_HOME} \
     -Dballerina.home=${GW_HOME} \
-    -jar ${args[0]} --api.usage.data.path=$GW_HOME/api-usage-data --b7a.http.accesslog.path=$GW_HOME/logs/access_logs --b7a.config.file=$GW_HOME/conf/micro-gw.conf ${args[@]:1}  2>&1 | tee -a $GW_HOME/logs/microgateway.log
+    -jar $args --api.usage.data.path=$GW_HOME/api-usage-data --b7a.http.accesslog.path=$GW_HOME/logs/access_logs --b7a.config.file=$MGW_CONF_DIR/micro-gw.conf 2>&1 | tee -a $GW_HOME/logs/microgateway.log
 EOF
 }
 
